"""
Crates zarrs for inputs not generated by the AFOLU flux model, to be used as contextual layers for zonal statistics using flox.

This should only need to be run once for each input

This needs to use the same zarr library version as flox zonal stats for some reason (v3.1.3),
rather than zarr v3.1.6, which is what all other scripts use.
So, the cluster has to use the zonal_stats creation options, either by including zonal_stats in the cluster name or
by including the --zonal_stats flag.

python -m src.utilities.create_cluster -n 50 -m 64 -cn vegetation_zonal_stats --zonal_stats
python -m src.LULUCF.scripts.zonal_statistics.create_contextual_zarrs -cn vegetation_zonal_stats -l X -ln "X zarr creation for zonal stats"

"""

import argparse
import time
import sys
import pandas as pd
import numpy as np
import boto3
import fsspec
import zarr

from dask.distributed import print
from datetime import date

# Project imports
from src.utilities import constants_and_names as cn
from src.utilities import log_utilities as lu
from src.utilities import universal_utilities as uu
from src.utilities import zarr_utilities as zu


def main(cluster_name, layers_to_process, no_upload, log_note=None):

    ### Step 1: Preparation

    # Model stage being run
    stage = 'zonal_stats_contextual_layer_zarr_creation'

    # Connects to Coiled cluster if not running locally and the named cluster exists
    cluster, client, run_local = uu.connect_to_Coiled_cluster(cluster_name, False)

    # Creates the log for the main function and populates it with basic run information
    main_logger, main_log_local_path, n_workers = lu.populate_main_log_header(client, cluster, log_note, run_local, 'N/A', stage)

    start_time = time.time() # Starting time for stage
    main_logger.info(f"Stage {stage} started at: {uu.timestr()}")
    main_logger.info(f"Vegetation model version: {cn.veg_model_version}")
    main_logger.info(f"Start year: {cn.first_model_year_annual}; end year: {cn.last_model_year_annual}")
    main_logger.info(f"Run date: {date.today().strftime("%Y%m%d")}")
    main_logger.info(f"no_upload: {no_upload}")

    layers_to_zarr = {}

    if 'adm0' in layers_to_process:  # Didn't use this script to create zarr; used notebook predecessor
        layers_to_zarr["adm0"] = {
            'zarr_date': cn.adm0_zarr_date,
            'zarr_dtype': cn.adm0_zarr_dtype,
            'geotif_dir': cn.adm0_geotif_path,
            'zarr_dir': cn.adm0_zarr_path,
            'test_chunk': cn.adm0_test_chunk
        }

    if 'pixel_area' in layers_to_process:
        layers_to_zarr["pixel_area"] = {
            'zarr_date': cn.pixel_area_zarr_date,
            'zarr_dtype': cn.pixel_area_zarr_dtype,
            'geotif_dir': cn.pixel_area_geotif_path,
            'zarr_dir': cn.pixel_area_zarr_path,
            'test_chunk': cn.pixel_area_test_chunk
        }

    if 'wdpa' in layers_to_process:  # Didn't use this script to create zarr; used notebook predecessor
        layers_to_zarr["wdpa"] = {
            'zarr_date': cn.WDPA_zarr_date,
            'zarr_dtype': cn.WDPA_zarr_dtype,
            'geotif_dir': cn.WDPA_geotif_path,
            'zarr_dir': cn.WDPA_zarr_path,
            'test_chunk': cn.WDPA_test_chunk
        }

    if 'brazil_biomes' in layers_to_process:  # Didn't use this script to create zarr; used notebook predecessor
        layers_to_zarr["brazil_biomes"] = {
            'zarr_date': cn.BRA_biomes_zarr_date,
            'zarr_dtype': cn.BRA_biomes_zarr_dtype,
            'geotif_dir': cn.BRA_biomes_geotif_path,
            'zarr_dir': cn.BRA_biomes_zarr_path,
            'test_chunk': cn.BRA_biomes_test_chunk
        }

    if 'cont_eco' in layers_to_process:  # Didn't use this script to create zarr; used notebook predecessor
        layers_to_zarr["cont_eco"] = {
            'zarr_date': cn.cont_eco_zarr_date,
            'zarr_dtype': cn.cont_eco_zarr_dtype,
            'geotif_dir': cn.cont_eco_geotif_path,
            'zarr_dir': cn.cont_eco_zarr_path,
            'test_chunk': cn.cont_eco_test_chunk
        }

    if 'landmark' in layers_to_process:
        layers_to_zarr["landmark"] = {
            'zarr_date': cn.landmark_zarr_date,
            'zarr_dtype': cn.landmark_zarr_dtype,
            'geotif_dir': cn.landmark_geotif_path,
            'zarr_dir': cn.landmark_zarr_path,
            'test_chunk': cn.landmark_test_chunk
        }

    if 'KBA' in layers_to_process:
        layers_to_zarr["KBA"] = {
            'zarr_date': cn.KBA_zarr_date,
            'zarr_dtype': cn.KBA_zarr_dtype,
            'geotif_dir': cn.KBA_geotif_path,
            'zarr_dir': cn.KBA_zarr_path,
            'test_chunk': cn.KBA_test_chunk
        }

    if 'watersheds' in layers_to_process:
        layers_to_zarr["watersheds"] = {
            'zarr_date': cn.watersheds_zarr_date,
            'zarr_dtype': cn.watersheds_zarr_dtype,
            'geotif_dir': cn.watersheds_geotif_path,
            'zarr_dir': cn.watersheds_zarr_path,
            'test_chunk': cn.watersheds_test_chunk
        }

    # I got alignment errors when I tried running SOC zonal stats with this.
    # Couldn't figure out why.
    # Tried in https://chatgpt.com/g/g-p-69399a7fcc808191b337d3fac695447c-afolu-flux-model/c/69c09184-06dc-8332-a90f-7bf0e803ea16
    if 'managed_land_Canada' in layers_to_process:
        layers_to_zarr["managed_land_Canada"] = {
            'zarr_date': cn.managed_land_CAN_zarr_date,
            'zarr_dtype': cn.managed_land_CAN_zarr_dtype,
            'geotif_dir': cn.managed_land_CAN_geotif_path,
            'zarr_dir': cn.managed_land_CAN_zarr_path,
            'test_chunk': cn.managed_land_CAN_test_chunk
        }

    if 'managed_land_USA' in layers_to_process:
        layers_to_zarr["managed_land_USA"] = {
            'zarr_date': cn.managed_land_USA_zarr_date,
            'zarr_dtype': cn.managed_land_USA_zarr_dtype,
            'geotif_dir': cn.managed_land_USA_geotif_path,
            'zarr_dir': cn.managed_land_USA_zarr_path,
            'test_chunk': cn.managed_land_USA_test_chunk
        }

    if 'drivers_of_loss' in layers_to_process:
        layers_to_zarr["drivers_of_loss"] = {
            'zarr_date': cn.drivers_of_loss_zarr_date,
            'zarr_dtype': cn.drivers_of_loss_zarr_dtype,
            'geotif_dir': cn.drivers_of_loss_geotif_path,
            'zarr_dir': cn.drivers_of_loss_zarr_path,
            'test_chunk': cn.drivers_of_loss_test_chunk
        }

    if 'first_year_LC_composite' in layers_to_process:
        layers_to_zarr["first_year_LC_composite"] = {
            'zarr_date': cn.first_year_LC_composite_zarr_date,
            'zarr_dtype': cn.first_year_LC_composite_zarr_dtype,
            'geotif_dir': cn.first_year_LC_composite_geotif_path,
            'zarr_dir': cn.first_year_LC_composite_zarr_path,
            'test_chunk': cn.first_year_LC_composite_test_chunk
        }

    main_logger.info(f"Contextual layers to zarr ({len(layers_to_zarr)} layers): {layers_to_zarr}")

    # Iterates through supplied contextual layers
    for layer_to_zarr, values in layers_to_zarr.items():

        main_logger.info(f"Processing {layer_to_zarr}: {uu.timestr()}")
        layer_start_time = time.time()

        # Get list of geotifs and convert to a series
        geotif_uris_list, geotif_count = uu.list_raster_full_paths_in_s3_folder_and_count(values['geotif_dir'])
        geotif_uris_series = pd.Series(geotif_uris_list)

        main_logger.info(f"  Input s3 geotif folder: {values['geotif_dir']}")
        main_logger.info(f"  First geotif in folder: {geotif_uris_series[0]}")
        main_logger.info(f"  Tile count in {layer_to_zarr}: {geotif_count}")

        main_logger.info(f"  Reading {layer_to_zarr}: {uu.timestr()}")
        # This now includes a comparison of the northwest pixel of each geotif and the corresponding pixel of the global ds
        # to make sure tiles aren't being flipped when they're combined by open_mfdataset,
        # which happened with at least pixel_area for three tiles.
        # Done with Claude session 'SOC chunk stats mismatch investigation'
        layer_xarray_chunks = zu.make_xarray_chunks(geotif_uris_series, cn.chunk_dims, main_logger)
        layer_xarray_chunks['band_data'] = layer_xarray_chunks['band_data'].astype(values['zarr_dtype'])

        main_logger.info(f"  Zarring {layer_to_zarr}: {uu.timestr()}")
        layer_xarray_chunks.to_zarr(values['zarr_dir'], mode='w')
        zu.remove_FillValue(values['zarr_dir'])  # Added per https://chatgpt.com/g/g-vK4oPfjfp-coding-assistant/c/6912af84-deb4-832d-81f0-da2b22b0737d to deal with FillValue problems

        layer_end_time = time.time()
        main_logger.info(f"  Finished zarring {layer_to_zarr}, took {round(layer_end_time - layer_start_time)} seconds: {uu.timestr()}")

        ### Checks contents of contextual zarr (no year dimension) in a specified chunk.
        ### It works even for zarrs that do not have global coverage (e.g., Brazil biomes)
        ### From https://chatgpt.com/g/g-p-69399a7fcc808191b337d3fac695447c-afolu-flux-model/c/6986043f-c8b0-832c-837f-7329873aa948

        # Points to the Zarr group
        fs = fsspec.filesystem("s3", anon=False)
        zarr_store = fs.get_mapper(values['zarr_dir'])
        zarr_group = zarr.open_group(zarr_store, mode="r")

        # Lists keys in zarr
        main_logger.info(f"  Zarr keys: {list(zarr_group.array_keys())}")

        # Tries reading coordinate arrays
        if "y" in zarr_group:
            y_coords = zarr_group["y"][:]
            main_logger.info(f"  y shape: {y_coords.shape}")
        else:
            sys.exit("No y coordinate array")

        if "x" in zarr_group:
            x_coords = zarr_group["x"][:]
            main_logger.info(f"  x shape: {x_coords.shape}")
        else:
            sys.exit("No x coordinate array")

        main_logger.info(f"{layer_to_zarr} x shape: {x_coords.shape}")
        main_logger.info(f"{layer_to_zarr} y shape: {y_coords.shape}")
        main_logger.info(f"{layer_to_zarr} x first 5 diffs: {np.diff(x_coords[:5])}")
        main_logger.info(f"{layer_to_zarr} y first 5 diffs: {np.diff(y_coords[:5])}")
        main_logger.info(f"{layer_to_zarr} unique x count: {len(np.unique(x_coords))}")
        main_logger.info(f"{layer_to_zarr} unique y count: {len(np.unique(y_coords))}")

        # Gets lat and long indices for chunk based on the indices of this zarr (as opposed to global zarr indices)
        lat_vals = y_coords  # usually descending
        lon_vals = x_coords  # usually ascending
        lat0, lat1 = zu.get_index_range(lat_vals, values['test_chunk'][3], values['test_chunk'][1], descending=True)
        lon0, lon1 = zu.get_index_range(lon_vals, values['test_chunk'][0], values['test_chunk'][2])

        # zarrs without time dimension have the variable name band_data
        var_name = 'band_data'

        # print(f"  Getting array for {test_chunk}")
        zarr_mapper_band_data = fs.get_mapper(f"{values['zarr_dir']}/{var_name}")
        zarr_array = zarr.open_array(zarr_mapper_band_data, mode="r")

        # Array from zarr chunk
        zarr_chunk_array = zarr_array[lat0:lat1, lon0:lon1]

        main_logger.info(f"Test chunk stats:")
        main_logger.info(f"  zarr_chunk_array: {zarr_chunk_array}")
        main_logger.info(f"  Min for {values['test_chunk']}: {float(np.nanmin(zarr_chunk_array))}")
        main_logger.info(f"  Mean for {values['test_chunk']}: {float(np.nanmean(zarr_chunk_array))}")
        main_logger.info(f"  Max for {values['test_chunk']}: {float(np.nanmax(zarr_chunk_array))}")
        main_logger.info(f"  Count for {values['test_chunk']}: {np.count_nonzero(zarr_chunk_array)}")

    end_time = time.time()
    main_logger.info(f"  Finished zarring {len(layers_to_zarr)} contextual layers, took {round(end_time - start_time)} seconds: {uu.timestr()}")

    s3_client = boto3.client("s3")  # Needs to be in the same function as the upload_file call
    log_name = f"{cn.combined_log}_main_{stage}_{time.strftime('%Y%m%d_%H_%M_%S')}__{layers_to_process}.log"
    s3_client.upload_file(main_log_local_path, "gfw2-data", Key=f"{cn.s3_log_path}{log_name}")


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Create global zarrs for contextual layers for zonal stats")
    parser.add_argument('-cn', '--cluster_name', help='Coiled cluster name')
    parser.add_argument('-l', '--layers_to_process', action='store', nargs='+', help='Contextual layers to convert to zarrs')
    parser.add_argument('-ln', '--log_note', help='Note to include in the log.')

    parser.add_argument('--no_upload', action='store_true', help='Do not save and upload outputs to s3')

    args = parser.parse_args()
    cluster_name = args.cluster_name
    layers_to_process = args.layers_to_process
    log_note = args.log_note

    no_upload = args.no_upload

    # Create the cluster with command line arguments
    main(cluster_name, layers_to_process, no_upload, log_note=log_note)